name: Release
on:
  create:
    tags:
      - "v*"


jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build project
        run: |
          make release VERSION=${{ github.ref }}

      - name: Create Release
        id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Yihctl ${{ github.ref }}
            draft: false
            prerelease: false

      - name: Upload Release darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/yihctl-${{ github.ref }}-darwin-amd64.zip
          asset_name: yihctl-${{ github.ref }}-darwin-amd64.zip
          asset_content_type: application/zip
      - name: Upload Release darwin amd64 sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/yihctl-${{ github.ref }}-darwin-amd64.zip.sha256sum
          asset_name: yihctl-${{ github.ref }}-darwin-amd64.zip.sha256sum
          asset_content_type: application/zip

      - name: Upload Release linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/yihctl-${{ github.ref }}-linux-amd64.zip
          asset_name: yihctl-${{ github.ref }}-linux-amd64.zip
          asset_content_type: application/zip
      - name: Upload Release darwin amd64 sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/yihctl-${{ github.ref }}-linux-amd64.zip.sha256sum
          asset_name: yihctl-${{ github.ref }}-linux-amd64.zip.sha256sum
          asset_content_type: application/zip

      - name: Upload Release linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/yihctl-${{ github.ref }}-windows-amd64.zip
          asset_name: yihctl-${{ github.ref }}-windows-amd64.zip
          asset_content_type: application/zip
      - name: Upload Release darwin amd64 sha256sum
        uses: actions/upload-release-asset@v1
        env:
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/yihctl-${{ github.ref }}-windows-amd64.zip.sha256sum
          asset_name: yihctl-${{ github.ref }}-windows-amd64.zip.sha256sum
          asset_content_type: application/zip
=======
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
>>>>>>> 32a1415eeb7060ec1753d44617fbcf95f4524f14
